spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


#Ambientes de prueba
#spring.datasource.url=jdbc:mysql://localhost:3306/backendcrall?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=


#Ambiente de producción 
spring.datasource.url=jdbc:mysql://uv4ohvd8nvzkwij6:A6moyO5GzLhbHvELJjL5@bvvtfutsbgeod4syhm4t-mysql.services.clever-cloud.com:3306/bvvtfutsbgeod4syhm4t
spring.datasource.username=uv4ohvd8nvzkwij6
spring.datasource.password=A6moyO5GzLhbHvELJjL5




#Ambiente de producción Railway
#spring.datasource.url=jdbc:mysql://root:VkwUEoiApAj75saPkR4Q@containers-us-west-119.railway.app:6986/railway?useSSL=false&serverTimezone=UTC
#spring.datasource.username=uv4ohvd8nvzkwij6
#spring.datasource.password=VkwUEoiApAj75saPkR4Q

# Variable que se usa para la firma de seguridad
jwt.secret = secret

#tiempo de expiración serial (12 horas) tiempo en seg
jwt.expiration = 7200